name: omnium_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de Estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  # cloud_functions: ^5.0.0 # Adicionar se for interagir com Functions do lado do cliente

  # Login Social
  google_sign_in: ^6.1.5 # Exemplo, o usuário pediu Facebook e Instagram
  flutter_facebook_auth: ^7.0.0
  # Para Instagram, pode ser necessário usar WebView ou uma API específica, se disponível

  # Armazenamento Local
  shared_preferences: ^2.2.0
  # flutter_secure_storage: ^9.0.0 # Para dados mais sensíveis

  # Imagem e Câmera
  image_picker: ^1.0.4
  camera: ^0.11.0+1 # Verificar compatibilidade e configuração por plataforma
  path_provider: ^2.1.1

  # Navegação
  go_router: ^14.2.0

  # Utilitários
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.0.1
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  # flutter_secure_screen: ^0.0.2 # Exemplo, verificar alternativas mais robustas/atualizadas

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.4
  mockito: ^5.4.2 # Para mocks em testes
  build_runner: ^2.4.9 # Para geração de código (mocks)

flutter:
  uses-material-design: true

  # assets:
  #   - .env
  #   - assets/images/
  #   - assets/fonts/

  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/MyCustomFont-Regular.ttf

